 <h1 class="firstHeading" id="firstHeading">std :: nested_exception :: nested_ptr</h1> <table class="t-dcl-begin"> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">STD :: Exception_ptr lồng nhau_ptr () const NoExcept;</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(kể từ C ++ 11)</span> </td> </tr> </table> <p>Trả về một con trỏ cho ngoại lệ được lưu trữ, nếu có.</p>
<h3 id="Parameters">) với giá trị ban đầu</h3> <p>Gán cho đã cho</p>
<h3 id="Return_value">phải sao cho một đối tượng thuộc loại</h3> <p>MỘT<code>std::exception_ptr</code>đến ngoại lệ được lưu trữ nếu một người được lưu trữ, mặc định-khởi kiện<code>std::exception_ptr</code>Nếu đối số đầu tiên là</p>
<div class="_attribution">
<p class="_attribution-p">© CPPReference.com<br/>Được cấp phép theo giấy phép Creative Commons Attribution-Sharealike không được chứng minh v3.0.<br/>
<a class="_attribution-link" href="https://en.cppreference.com/w/cpp/error/nested_exception/nested_ptr">https://en.cppreference.com/w/cpp/error/nested_exception/nested_ptr</a>
</p>
</div>
