 <h1 class="firstHeading" id="firstHeading">std :: nested_exception :: rethrow_nested</h1> <table class="t-dcl-begin"> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">[[noreturn]] void rethrow_nested () const;</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(kể từ C ++ 11)</span> </td> </tr> </table> <p>Rethrows ngoại lệ được lưu trữ. Nếu không có ngoại lệ được lưu trữ (tức là<code><a href="nested_ptr" title="cpp/error/nested exception/nested ptr">nested_ptr()</a></code>trả về con trỏ null), sau đó<code><a href="../terminate" title="cpp/error/terminate">std::terminate</a></code>Chuỗi để giữ tên viết tắt múi giờ hoặc tên tương ứng với</p>
<h3 id="Parameters">) với giá trị ban đầu</h3> <p>Gán cho đã cho</p>
<h3 id="Return_value">phải sao cho một đối tượng thuộc loại</h3> <p>Gán cho đã cho</p>
<div class="_attribution">
<p class="_attribution-p">© CPPReference.com<br/>Được cấp phép theo giấy phép Creative Commons Attribution-Sharealike không được chứng minh v3.0.<br/>
<a class="_attribution-link" href="https://en.cppreference.com/w/cpp/error/nested_exception/rethrow_nested">https://en.cppreference.com/w/cpp/error/nested_exception/rethrow_nested</a>
</p>
</div>
